/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/chessboard.glb -o src/components/Chessboard.jsx -r public -k 
*/

import React, { useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Vector3 } from 'three'
import { Pawn } from './Pawn'

export function Chessboard(props) {
  const group = useRef()
  const bAPawn = useRef()
  const bBPawn = useRef()
  const bCPawn = useRef()
  const bDPawn = useRef()
  const bEPawn = useRef()
  const bFPawn = useRef()
  const bGPawn = useRef()
  const bHPawn = useRef()
  const rook = useRef()


  
  const [active, setActive] = useState({
    activePiece: null
  })
  const { nodes, materials, animations } = useGLTF('/assets/chessboard.glb')
  const { actions } = useAnimations(animations, group)

  const getCenterPoint = (mesh) => {
    var geometry = mesh.geometry;
    geometry.computeBoundingBox();
    var center = new Vector3();
    geometry.boundingBox.getCenter( center );
    mesh.localToWorld( center );
    return center;
  }
  const activatePiece = (ref) => {
    console.log(ref.current.geometry)
    if(active.activePiece == null) {
      ref.current.position.y += 1.4
      setActive({activePiece: ref})
    } else {
      active.activePiece.current.position.y -= 1.4
      setActive({activePiece: null})
    }
    
    // ref.current.position.z += 0.89957142857
  }
  window.addEventListener('click', e => {
    // console.log(materials)
  })


  return (
    <group ref={group} {...props}  dispose={null} castShadow>
      <group name="Scene" scale={[0.2,0.2,0.2]} >
        <group>
          <group name="main" position={[0.439, -0.483, 0.051]} scale={[11.994, 11.595, 11.994]} >
            <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.blacksquare} receiveShadow={true}/>
            <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.whitesquare} receiveShadow={true}/>
          </group>
          <mesh receiveShadow={true} name="outer" geometry={nodes.outer.geometry} material={materials.Material} position={[0.439, -0.495, 0.051]} scale={[4.198, 11.994, 4.198]} />
        </group>
        <group name='letters'>
          <mesh name="letter_B" geometry={nodes.letter_B.geometry} material={materials['Material.002']} position={[-1.81, -0.238, 3.957]} scale={11.994} />
          <mesh name="letter_C" geometry={nodes.letter_C.geometry} material={materials['Material.002']} position={[-0.911, -0.238, 3.957]} scale={11.994} />
          <mesh name="letter_1" geometry={nodes.letter_1.geometry} material={materials['Material.002']} position={[-3.453, -0.238, 3.199]} scale={11.994} />
          <mesh name="letter_3" geometry={nodes.letter_3.geometry} material={materials['Material.002']} position={[-3.453, -0.238, 1.4]} scale={11.994} />
          <mesh name="letter_4" geometry={nodes.letter_4.geometry} material={materials['Material.002']} position={[-3.453, -0.238, 0.5]} scale={11.994} />
          <mesh name="letter_6" geometry={nodes.letter_6.geometry} material={materials['Material.002']} position={[-3.453, -0.238, -1.299]} scale={11.994} />
          <mesh name="letter_5" geometry={nodes.letter_5.geometry} material={materials['Material.002']} position={[-3.453, -0.238, -0.399]} scale={11.994} />
          <mesh name="letter_7" geometry={nodes.letter_7.geometry} material={materials['Material.002']} position={[-3.453, -0.238, -2.198]} scale={11.994} />
          <mesh name="letter_8" geometry={nodes.letter_8.geometry} material={materials['Material.002']} position={[-3.453, -0.238, -3.098]} scale={11.994} />
          <mesh name="letter_D" geometry={nodes.letter_D.geometry} material={materials['Material.002']} position={[-0.011, -0.238, 3.957]} scale={11.994} />
          <mesh name="letter_2" geometry={nodes.letter_2.geometry} material={materials['Material.002']} position={[-3.453, -0.238, 2.3]} scale={11.994} />
          <mesh name="letter_E" geometry={nodes.letter_E.geometry} material={materials['Material.002']} position={[0.889, -0.238, 3.957]} scale={11.994} />
          <mesh name="letter_F" geometry={nodes.letter_F.geometry} material={materials['Material.002']} position={[1.788, -0.238, 3.957]} scale={11.994} />
          <mesh name="letter_G" geometry={nodes.letter_G.geometry} material={materials['Material.002']} position={[2.688, -0.238, 3.957]} scale={11.994} />
          <mesh name="letter_H" geometry={nodes.letter_H.geometry} material={materials['Material.002']} position={[3.587, -0.238, 3.957]} scale={11.994} />
          <mesh name="letter_A" geometry={nodes.letter_A.geometry} material={materials['Material.002']} position={[-2.71, -0.238, 3.957]} scale={1.194} />
          <mesh name="letter_B001" geometry={nodes.letter_B001.geometry} material={materials['Material.002']} position={[-1.81, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_C001" geometry={nodes.letter_C001.geometry} material={materials['Material.002']} position={[-0.911, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_H001" geometry={nodes.letter_H001.geometry} material={materials['Material.002']} position={[3.587, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_G001" geometry={nodes.letter_G001.geometry} material={materials['Material.002']} position={[2.688, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_F001" geometry={nodes.letter_F001.geometry} material={materials['Material.002']} position={[1.788, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_D001" geometry={nodes.letter_D001.geometry} material={materials['Material.002']} position={[-0.011, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_E001" geometry={nodes.letter_E001.geometry} material={materials['Material.002']} position={[0.889, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_1001" geometry={nodes.letter_1001.geometry} material={materials['Material.002']} position={[4.331, -0.238, 3.199]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_2001" geometry={nodes.letter_2001.geometry} material={materials['Material.002']} position={[4.331, -0.238, 2.3]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_3001" geometry={nodes.letter_3001.geometry} material={materials['Material.002']} position={[4.331, -0.238, 1.4]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_A2" geometry={nodes.letter_A2.geometry} material={materials['Material.002']} position={[-2.71, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={1.194} />
          <mesh name="letter_4001" geometry={nodes.letter_4001.geometry} material={nodes.letter_4001.material} position={[4.331, -0.238, 0.5]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_5001" geometry={nodes.letter_5001.geometry} material={materials['Material.002']} position={[4.331, -0.238, -0.399]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_6001" geometry={nodes.letter_6001.geometry} material={materials['Material.002']} position={[4.331, -0.238, -1.299]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_7001" geometry={nodes.letter_7001.geometry} material={materials['Material.002']} position={[4.331, -0.238, -2.198]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
          <mesh name="letter_8001" geometry={nodes.letter_8001.geometry} material={materials['Material.002']} position={[4.331, -0.238, -3.098]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        </group>
        <group name='planes'>
          <mesh name="Plane" onClick={e => {
            // console.log(e.point)
          }} geometry={nodes.Plane.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane024" geometry={nodes.Plane024.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane025" geometry={nodes.Plane025.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane026" geometry={nodes.Plane026.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane028" geometry={nodes.Plane028.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane030" geometry={nodes.Plane030.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane031" geometry={nodes.Plane031.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane032" geometry={nodes.Plane032.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane033" geometry={nodes.Plane033.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane034" geometry={nodes.Plane034.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane035" geometry={nodes.Plane035.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane036" geometry={nodes.Plane036.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane037" geometry={nodes.Plane037.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane038" geometry={nodes.Plane038.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane039" geometry={nodes.Plane039.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane040" geometry={nodes.Plane040.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane041" geometry={nodes.Plane041.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane042" geometry={nodes.Plane042.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane043" geometry={nodes.Plane043.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane044" geometry={nodes.Plane044.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane045" geometry={nodes.Plane045.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane046" geometry={nodes.Plane046.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane047" geometry={nodes.Plane047.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane048" geometry={nodes.Plane048.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane049" geometry={nodes.Plane049.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane050" geometry={nodes.Plane050.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane051" geometry={nodes.Plane051.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane052" geometry={nodes.Plane052.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane053" geometry={nodes.Plane053.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane054" geometry={nodes.Plane054.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane055" geometry={nodes.Plane055.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane056" geometry={nodes.Plane056.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane057" geometry={nodes.Plane057.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane058" geometry={nodes.Plane058.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane059" geometry={nodes.Plane059.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane060" geometry={nodes.Plane060.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane061" geometry={nodes.Plane061.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane062" geometry={nodes.Plane062.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
          <mesh name="Plane063" geometry={nodes.Plane063.geometry} material={materials.transparent} position={[0.43, -0.123, 0.045]} scale={3.622} />
        </group>
        <group name='blackPieces'>
          <Pawn pref={bAPawn} hoverMaterial={materials.black_marble} onClick={() => activatePiece(bAPawn)} name="bAPawn" geometry={nodes.pawn.geometry} material={materials.black} position={[-2.71, -0.133, -2.198]} scale={0.22} />
          <Pawn pref={bBPawn} hoverMaterial={materials.black_marble} onClick={() => activatePiece(bBPawn)} name="bBPawn" geometry={nodes.pawn.geometry} material={materials.black} position={[-1.81042857143, -0.133, -2.198]} scale={0.22} />
          <Pawn pref={bCPawn} hoverMaterial={materials.black_marble} onClick={() => activatePiece(bCPawn)} name="bCPawn" geometry={nodes.pawn.geometry} material={materials.black} position={[-0.9108571428599999, -0.133, -2.198]} scale={0.22} />
          <Pawn pref={bDPawn} hoverMaterial={materials.black_marble} onClick={() => activatePiece(bDPawn)} name="bDPawn" geometry={nodes.pawn.geometry} material={materials.black} position={[-0.011285714289999804, -0.133, -2.198]} scale={0.22} />
          <Pawn pref={bEPawn} hoverMaterial={materials.black_marble} onClick={() => activatePiece(bEPawn)} name="bEPawn" geometry={nodes.pawn.geometry} material={materials.black} position={[0.8882857142800002, -0.133, -2.198]} scale={0.22} />
          <Pawn pref={bFPawn} hoverMaterial={materials.black_marble} onClick={() => activatePiece(bFPawn)} name="bFPawn" geometry={nodes.pawn.geometry} material={materials.black} position={[1.7878571428500003, -0.133, -2.198]} scale={0.22} />
          <Pawn pref={bGPawn} hoverMaterial={materials.black_marble} onClick={() => activatePiece(bGPawn)} name="bGPawn" geometry={nodes.pawn.geometry} material={materials.black} position={[2.6874285714200004, -0.133, -2.198]} scale={0.22} />
          <Pawn pref={bHPawn} hoverMaterial={materials.black_marble} onClick={() => activatePiece(bHPawn)} name="bHPawn" geometry={nodes.pawn.geometry} material={materials.black} position={[3.5869999999900006, -0.133, -2.198]} scale={0.22} />
          <mesh ref={rook} onClick={() => activatePiece(rook)} name="bishop" geometry={nodes.bishop.geometry} material={materials.black} position={[-0.911, -0.133, -3.098]} scale={0.175} />
          <mesh name="bishop2" geometry={nodes.bishop.geometry} material={materials.black} position={[1.7878571428500003, -0.133, -3.098]} scale={0.175} />
          <mesh name="knight" geometry={nodes.knight.geometry} material={materials.black} position={[-1.752, -0.133, -3.098]} scale={0.276} />
          <mesh name="knight2" geometry={nodes.knight.geometry} material={materials.black} position={[2.6874285714200004, -0.133, -3.098]} scale={0.276} />
          <mesh name="rook"  geometry={nodes.rook.geometry} material={materials.black} position={[-2.71, -0.133, -3.098]} scale={0.16} />
          <mesh name="rook2" geometry={nodes.rook.geometry} material={materials.black} position={[3.5869999999900006, -0.133, -3.098]} scale={0.16} />
          <mesh name="king" geometry={nodes.king.geometry} material={materials.black} position={[0.889, -0.133, -3.098]} scale={0.059} />
          <mesh name="queen" geometry={nodes.queen.geometry} material={materials.black} position={[-0.011, -0.133, -3.098]} scale={0.151} />

        </group>
          <group name='whitePieces'>
        </group>
        
        
      </group>
      
      </group>

      // loaded but not used models
      // <mesh name="rook001" geometry={nodes.rook001.geometry} material={materials.black} position={[-2.71, -0.133, 3.199]} scale={0.16} /><mesh name="rook001" geometry={nodes.rook001.geometry} material={materials.black} position={[-2.71, -0.133, 3.199]} scale={0.16} />
      // <mesh name="pawn" geometry={nodes.pawn.geometry} material={materials.black} position={[-2.71, -0.133, -2.198]} scale={0.22} />
      // <mesh name="black_pawn" geometry={nodes.black_pawn.geometry} material={materials.black_marble} position={[3.587, -0.133, -2.188]} scale={0.22} />
        // <mesh name="pawn001" geometry={nodes.pawn001.geometry} material={materials.black_marble} position={[-8.104, -0.162, 0]} scale={0.22} />
  )
}

useGLTF.preload('/assets/chessboard.glb')
