/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/chessboard.glb -o src/components/Chessboard.jsx -r public -k 
*/

import React, { useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Vector3 } from 'three'

export function Chessboard(props) {
  const group = useRef()
  const rook = useRef()
  const [state, setState] = useState({
    v3: new Vector3(0,0,0)
  })
  const { nodes, materials, animations } = useGLTF('/assets/chessboard.glb')
  const { actions } = useAnimations(animations, group)

  const getCenterPoint = (mesh) => {
    var geometry = mesh.geometry;
    geometry.computeBoundingBox();
    var center = new Vector3();
    geometry.boundingBox.getCenter( center );
    mesh.localToWorld( center );
    return center;
  }
  const updateRook = () => {
    console.log(rook.current)
    rook.current.position.x += 0.89957142857
    rook.current.position.z += 0.89957142857
    if ( rook.current.position.x>0) {
      rook.current.scale;
    }

  }

  return (
    <group ref={group} {...props}  dispose={null} castShadow>
      <group name="Scene" scale={[0.2,0.2,0.2]} >
        <group>
          <group name="main" position={[0.439, -0.483, 0.051]} scale={[11.994, 11.595, 11.994]}>
            <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.blacksquare} />
            <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.whitesquare} />
          </group>
          <mesh name="outer" geometry={nodes.outer.geometry} material={materials.Material} position={[0.439, -0.495, 0.051]} scale={[4.198, 11.994, 4.198]} />
        </group>
        <mesh name="letter_B" geometry={nodes.letter_B.geometry} material={materials['Material.002']} position={[-1.81, -0.238, 3.957]} scale={11.994} />
        <mesh name="letter_C" geometry={nodes.letter_C.geometry} material={materials['Material.002']} position={[-0.911, -0.238, 3.957]} scale={11.994} />
        <mesh name="letter_1" geometry={nodes.letter_1.geometry} material={materials['Material.002']} position={[-3.453, -0.238, 3.199]} scale={11.994} />
        <mesh name="letter_3" geometry={nodes.letter_3.geometry} material={materials['Material.002']} position={[-3.453, -0.238, 1.4]} scale={11.994} />
        <mesh name="letter_4" geometry={nodes.letter_4.geometry} material={materials['Material.002']} position={[-3.453, -0.238, 0.5]} scale={11.994} />
        <mesh name="letter_6" geometry={nodes.letter_6.geometry} material={materials['Material.002']} position={[-3.453, -0.238, -1.299]} scale={11.994} />
        <mesh name="letter_5" geometry={nodes.letter_5.geometry} material={materials['Material.002']} position={[-3.453, -0.238, -0.399]} scale={11.994} />
        <mesh name="letter_7" geometry={nodes.letter_7.geometry} material={materials['Material.002']} position={[-3.453, -0.238, -2.198]} scale={11.994} />
        <mesh name="letter_8" geometry={nodes.letter_8.geometry} material={materials['Material.002']} position={[-3.453, -0.238, -3.098]} scale={11.994} />
        <mesh name="letter_D" geometry={nodes.letter_D.geometry} material={materials['Material.002']} position={[-0.011, -0.238, 3.957]} scale={11.994} />
        <mesh name="letter_2" geometry={nodes.letter_2.geometry} material={materials['Material.002']} position={[-3.453, -0.238, 2.3]} scale={11.994} />
        <mesh name="letter_E" geometry={nodes.letter_E.geometry} material={materials['Material.002']} position={[0.889, -0.238, 3.957]} scale={11.994} />
        <mesh name="letter_F" geometry={nodes.letter_F.geometry} material={materials['Material.002']} position={[1.788, -0.238, 3.957]} scale={11.994} />
        <mesh name="letter_G" geometry={nodes.letter_G.geometry} material={materials['Material.002']} position={[2.688, -0.238, 3.957]} scale={11.994} />
        <mesh name="letter_H" geometry={nodes.letter_H.geometry} material={materials['Material.002']} position={[3.587, -0.238, 3.957]} scale={11.994} />
        <mesh name="letter_A" geometry={nodes.letter_A.geometry} material={materials['Material.002']} position={[-2.71, -0.238, 3.957]} scale={1.194} />
        <mesh name="letter_B001" geometry={nodes.letter_B001.geometry} material={materials['Material.002']} position={[-1.81, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_C001" geometry={nodes.letter_C001.geometry} material={materials['Material.002']} position={[-0.911, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_H001" geometry={nodes.letter_H001.geometry} material={materials['Material.002']} position={[3.587, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_G001" geometry={nodes.letter_G001.geometry} material={materials['Material.002']} position={[2.688, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_F001" geometry={nodes.letter_F001.geometry} material={materials['Material.002']} position={[1.788, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_D001" geometry={nodes.letter_D001.geometry} material={materials['Material.002']} position={[-0.011, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_E001" geometry={nodes.letter_E001.geometry} material={materials['Material.002']} position={[0.889, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_1001" geometry={nodes.letter_1001.geometry} material={materials['Material.002']} position={[4.331, -0.238, 3.199]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_2001" geometry={nodes.letter_2001.geometry} material={materials['Material.002']} position={[4.331, -0.238, 2.3]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_3001" geometry={nodes.letter_3001.geometry} material={materials['Material.002']} position={[4.331, -0.238, 1.4]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_A2" geometry={nodes.letter_A2.geometry} material={materials['Material.002']} position={[-2.71, -0.238, -3.855]} rotation={[Math.PI, 0, Math.PI]} scale={1.194} />
        <mesh name="letter_4001" geometry={nodes.letter_4001.geometry} material={nodes.letter_4001.material} position={[4.331, -0.238, 0.5]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_5001" geometry={nodes.letter_5001.geometry} material={materials['Material.002']} position={[4.331, -0.238, -0.399]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_6001" geometry={nodes.letter_6001.geometry} material={materials['Material.002']} position={[4.331, -0.238, -1.299]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_7001" geometry={nodes.letter_7001.geometry} material={materials['Material.002']} position={[4.331, -0.238, -2.198]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="letter_8001" geometry={nodes.letter_8001.geometry} material={materials['Material.002']} position={[4.331, -0.238, -3.098]} rotation={[Math.PI, 0, Math.PI]} scale={11.994} />
        <mesh name="black_pawn" geometry={nodes.black_pawn.geometry} material={materials.black_marble} position={[3.587, -0.133, -2.188]} scale={0.22} />
        <mesh name="pawn" geometry={nodes.pawn.geometry} material={materials.black} position={[-2.71, -0.133, -2.198]} scale={0.22} />
        <mesh name="pawn001" geometry={nodes.pawn001.geometry} material={materials.black_marble} position={[-8.104, -0.162, 0]} scale={0.22} />
        <mesh name="bishop" geometry={nodes.bishop.geometry} material={materials.black} position={[-0.911, -0.133, -3.098]} scale={0.175} />
        <mesh name="king" geometry={nodes.king.geometry} material={materials.black} position={[0.889, -0.133, -3.098]} scale={0.059} />
        <mesh name="knight" geometry={nodes.knight.geometry} material={materials.black} position={[-1.752, -0.133, -3.098]} scale={0.276} />
        <mesh name="queen" geometry={nodes.queen.geometry} material={materials.black} position={[-0.011, -0.133, -3.098]} scale={0.151} />
        <mesh ref={rook} name="rook" onClick={updateRook} geometry={nodes.rook.geometry} material={materials.black} position={[-2.71, -0.133, -3.098]} scale={0.16} />
        <mesh name="rook001" geometry={nodes.rook001.geometry} material={materials.black} position={[-2.71, -0.133, 3.199]} scale={0.16} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/chessboard.glb')
