/* eslint-disable react/no-unknown-property */
/* eslint-disable react/prop-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 pawn.glb 
*/
import React from 'react'
import { useRef, useState } from 'react'
import {  useFrame, useThree } from '@react-three/fiber'

import { useGLTF } from '@react-three/drei'

export function Pawn({pref, material, hoverMaterial, ...props}) { 
  const mesh = useRef()
  const { viewport } = useThree()
  const [hovered, setHover] = useState(false)
  const [active, setActive] = useState(0)
  // useFrame(() => (pref.current.rotation.z = pref.current.rotation.x += 0.01))
  
  
  return (
      <mesh 
        {...props}
        ref={pref}
        material={hovered || active ? hoverMaterial: material}
        // scale={(viewport.width / 5) * (active ? 1.5 : 1)}
        // onClick={(e) => {
        //     setActive((prev) => prev+10)
        //     // console.log(pref)
        //   }
        // }
        onPointerOver={(e) => setHover(true)}
        onPointerOut={(e) => setHover(false)} 
        />

      )
  }
    // <mesh geometry={nodes.Plane.geometry} material={materials.Board} position={[-1.455, 0, -1.697]} scale={-37.648} />