/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/the_smoking_room.glb -o src/components/SmokingRoom.jsx -r public -k 
Author: The Hallwyl Museum (Hallwylska museet) (https://sketchfab.com/TheHallwylMuseum)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-smoking-room-2247ed77976a40b6ae81271cd6b149c8
Title: The Smoking Room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/the_smoking_room.glb')
  return (
    <group {...props} dispose={null} receiveShadow>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.245}>
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.model_Material_u1_v1} />
        <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.model_Material_u1_v1} />
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.model_Material_u1_v1} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.model_Material_u1_v1} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.model_Material_u1_v1} />
        <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.model_Material_u1_v1} />
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.model_Material_u1_v1} />
        <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.model_Material_u1_v1} />
        <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.model_Material_u1_v1} />
        <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.model_Material_u1_v1} />
        <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.model_Material_u1_v1} />
        <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.model_Material_u1_v1} />
        <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.model_Material_u1_v1} />
        <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.model_Material_u1_v1} />
      </group>
    </group>
  )
}

useGLTF.preload('/the_smoking_room.glb')
