/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/table.glb -o src/components/Table.jsx -r public -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Table(props) {
  const { nodes, materials } = useGLTF('/assets/table.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Table" geometry={nodes.Table.geometry} material={materials['20040_PedestalBreakfastTable']} position={[0.439, -13.568, 0.051]} rotation={[Math.PI / 2, 0, 0]} scale={[0.121, 0.121, 0.174]} />
    </group>
  )
}

useGLTF.preload('/assets/table.glb')
